[package]
name = "rusty_ranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap  ={version = "3.1.0", features = ["derive"]}
tui = "0.17"
crossterm = "0.22"
dirs = "4.0.0"
